In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [4]:
np_num = np_array_2d[0:,0].astype(int)

In [5]:
np_1 = np_num%2

In [6]:
np_2 = (np_1 == 1)

In [7]:
np_3 = np_array_2d[np_2]

In [8]:
np_3[0:,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [3]:
np_array = np.array([
[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]
])

In [30]:
np_array[np_array < 50] = -1

In [31]:
np_array[np_array == 50] = 0

In [32]:
np_array[np_array > 50] = 1

In [33]:
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [4]:
np_array<50

array([[False, False, False,  True,  True],
       [False,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False, False,  True,  True],
       [False,  True, False,  True, False]])