Substting is to pick out a subset inside an array or a list. The subset can be a single data set or a range of data sets.
Indexing is the act of choosing a single data set by specifying the position the data set is using numbers (index).
Slicing  is to select a range of data sets from a list or an array.
Masking is a way of subsetting, by specifying conditions, masking can exclude the False and allowing only True to be seen.


In [1]:
import numpy as np

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [11]:
np_num = np_array_2d[0:,0].astype(int)
#print(np_num)

In [19]:
np_1 = np_num%2
print(np_1)

[1 1 0 0 1 1 0 0 0 1]


In [16]:
np_2 = (np_1 == 1)
print(np_2)

[ True  True False False  True  True False False False  True]


In [20]:
np_3 = np_array_2d[np_1==1]

In [21]:
np_3[0:,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [24]:
np_array = np.array([
[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]
])

In [30]:
np_array[np_array < 50] = -1

In [10]:
np_array[np_array == 50] = 0

In [11]:
np_array[np_array > 50] = 1

In [12]:
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
